import {releaseReservation,applyPaymentEvent} from '../src/lib/payments';
import type Stripe from 'stripe';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {totals,estimateCoins,nextDrop,materials,conditions} from '../src/lib/catalog';
import {checkoutSchema,tradeSchema,applicationSchema} from '../src/lib/validation';
import {initialState,walletBalance,adjustWallet} from '../src/lib/db';
test('coin redemption is capped at 25% of merchandise, never shipping',()=>{assert.deepEqual(totals(1999,10000,true),{subtotal:1999,redeemed:499,shipping:99,total:1599});assert.equal(totals(4000,250,true).redeemed,250);assert.equal(totals(4000,10000,false).redeemed,0);assert.equal(totals(2500,0,true).shipping,0);});
test('estimator is deterministic and ignores unsupported inputs',()=>{assert.deepEqual(estimateCoins(materials[0],conditions[0],2),{low:270,high:360});assert.equal(estimateCoins('invalid',conditions[0],2).high,0);assert.equal(estimateCoins(materials[0],conditions[0],-1).high,0);});
test('drop recurrence is anchored at 14 days, not reset per browser visit',()=>{const anchor=Date.parse('2026-10-09T18:00:00+05:30');assert.equal(nextDrop(anchor-1000),anchor);assert.equal(nextDrop(anchor+1000),anchor+14*86400000);});
test('checkout rejects invalid quantity, arbitrary size and empty cart',()=>{assert.equal(checkoutSchema.safeParse({items:[]}).success,false);const item=checkoutSchema.shape.items.element;assert.equal(item.safeParse({id:'utility-shacket',size:'M',quantity:-1}).success,false);assert.equal(item.safeParse({id:'utility-shacket',size:'HUGE',quantity:1}).success,false);assert.equal(item.safeParse({id:'utility-shacket',size:'M',quantity:1.5}).success,false);});
test('home pickup minimum and stale dates are server validated',()=>{const base={name:'Sample Visitor',phone:'+919000000000',email:'sample@example.com',material:materials[0],condition:conditions[0],weight:1,method:'pickup',city:'Pune',address:'Sample address only',date:'2099-10-10',consent:true};assert.equal(tradeSchema.safeParse(base).success,false);assert.equal(tradeSchema.safeParse({...base,weight:2}).success,true);assert.equal(tradeSchema.safeParse({...base,method:'dropoff'}).success,true);assert.equal(tradeSchema.safeParse({...base,weight:2,date:'2020-01-01'}).success,false);});
test('confirmed expiry releases reserved inventory and coins exactly once',()=>{const s=initialState();s.accounts.a={id:'a',coins:0,created:'',ledger:[]};const before=s.stock['utility-shacket:M'];s.orders.push({id:'o',accountId:'a',requestId:'r',status:'pending',created:'',expires:0,items:[{id:'utility-shacket',size:'M',quantity:1,name:'Shacket',price:3490}],subtotal:3490,redeemed:250,shipping:0,total:3240,customer:{},demo:false});releaseReservation(s,s.orders[0]);assert.equal(s.stock['utility-shacket:M'],before+1);assert.equal(s.accounts.a.liveCoins,250);releaseReservation(s,s.orders[0]);assert.equal(s.accounts.a.liveCoins,250);assert.equal(s.stock['utility-shacket:M'],before+1);});
test('designer portfolio must use HTTPS and consent is mandatory',()=>{const p={track:'designer',name:'Demo Designer',email:'demo@example.com',phone:'+919000000000',portfolio:'javascript:alert(1)',pitch:'An original denim and brocade capsule.',consent:true};assert.equal(applicationSchema.safeParse(p).success,false);assert.equal(applicationSchema.safeParse({...p,portfolio:'https://example.com/portfolio'}).success,true);assert.equal(applicationSchema.safeParse({...p,portfolio:'https://example.com',consent:false}).success,false);});

test('demo coins cannot be spent as live rewards',()=>{const a={id:'a',coins:250,created:'',ledger:[]};assert.equal(walletBalance(a,false),0);adjustWallet(a,40,'Verified trade',false);assert.equal(walletBalance(a,true),250);assert.equal(walletBalance(a,false),40);});
test('size inventory totals match advertised sample stock',()=>{const s=initialState();assert.equal(Object.entries(s.stock).filter(([key])=>key.startsWith('utility-shacket:')).reduce((n,[,v])=>n+v,0),12);});
test('payment events verify amount, reject foreign sessions and are idempotent',()=>{const s=initialState();s.accounts.a={id:'a',coins:250,liveCoins:0,created:'',ledger:[]};s.orders.push({id:'o',accountId:'a',requestId:'r',status:'pending',created:'',expires:0,items:[],subtotal:1000,redeemed:0,shipping:0,total:1000,customer:{},demo:false,sessionId:'cs_correct'});const event={id:'evt_1',type:'checkout.session.completed',data:{object:{id:'cs_correct',metadata:{orderId:'o'},payment_status:'paid',amount_total:999,currency:'inr'}}} as unknown as Stripe.Event;assert.throws(()=>applyPaymentEvent(s,event),/amount mismatch/);const session=event.data.object as Stripe.Checkout.Session;session.amount_total=100000;session.id='cs_foreign';assert.throws(()=>applyPaymentEvent(s,event),/session mismatch/);session.id='cs_correct';applyPaymentEvent(s,event);applyPaymentEvent(s,event);assert.equal(s.orders[0].status,'paid');assert.equal(s.webhooks.length,1);});
