'use client';
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {ShoppingBag,Menu,Coins,Minus,Plus,Trash2,UserRound,ArrowUpRight,MoveUpRight} from 'lucide-react';
import {useShop} from './providers';
import {Modal,Arrow} from './ui';
import {getProduct,money,whatsapp} from '@/lib/catalog';
const nav=[['The Drop','/shop'],['Trace a Thread','/passport'],['Tukda Bank','/bank'],['Rebind Bar','/rebind-bar'],['Our Impact','/impact'],['Join the Fold','/careers']];
export function Header(){const pathname=usePathname(),[menu,setMenu]=useState(false);const {cart,setCartOpen,account}=useShop();return <><a href="#main" className="skip-link">Skip to content</a><div className="announcement"><span>OLD THREADS. NEW POSSIBILITIES.</span><Link href="/careers#challenges">Circular Design Sprint ’26 <span>— Explore the sample challenge</span> <ArrowUpRight size={14}/></Link></div><header className="site-header"><Link href="/" className="wordmark" aria-label="Sūtra Rebind home">sūtra<span>REBIND</span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,href])=><Link key={href} href={href} className={pathname===href?'active':''}>{label}</Link>)}</nav><div className="header-actions"><Link href="/bank" className="coin-pill" aria-label={`${account?.coins??0} Tukda coins`}><Coins size={16}/><span>{account?.coins??'—'}</span></Link><Link href="/account" className="icon-button account-icon" aria-label="Your account"><UserRound size={20}/></Link><button className="icon-button bag-button" onClick={()=>setCartOpen(true)} aria-label={`Open bag, ${cart.reduce((s,i)=>s+i.quantity,0)} items`}><ShoppingBag size={21}/><span>{cart.reduce((s,i)=>s+i.quantity,0)}</span></button><button className="icon-button mobile-menu" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button></div></header><Modal open={menu} onOpenChange={setMenu} title="Explore Sūtra" drawer><nav className="mobile-links">{[...nav,['Contact','/contact'],['Your account','/account']].map(([label,href])=><Link href={href} key={href} onClick={()=>setMenu(false)}>{label}<Arrow/></Link>)}</nav></Modal><CartDrawer/></>;}
function CartDrawer(){const {cart,update,cartOpen,setCartOpen}=useShop();const subtotal=cart.reduce((n,i)=>n+(getProduct(i.id)?.price??0)*i.quantity,0);return <Modal open={cartOpen} onOpenChange={setCartOpen} title={`Your next chapter (${cart.reduce((n,i)=>n+i.quantity,0)})`} drawer><div className="cart-body">{cart.length===0?<div className="empty-state"><ShoppingBag size={48}/><h3>A little room for reinvention.</h3><p>Your bag is waiting for its first story.</p><Link href="/shop" className="button primary" onClick={()=>setCartOpen(false)}>Explore the drop <Arrow/></Link></div>:<>{cart.map(i=>{const p=getProduct(i.id)!;return <article className="cart-item" key={i.id+i.size}><Link href={`/shop/${p.id}`} onClick={()=>setCartOpen(false)}><Image src={p.image} alt={p.name} width={100} height={128} style={{objectPosition:p.imagePosition}}/></Link><div><p className="eyebrow">{p.category} / {i.size}</p><Link href={`/shop/${p.id}`} onClick={()=>setCartOpen(false)}><h3>{p.name}</h3></Link><p>{money(p.price)}</p><div className="quantity"><button aria-label={`Remove one ${p.name}`} onClick={()=>update(i.id,i.size,i.quantity-1)}><Minus size={14}/></button><span>{i.quantity}</span><button aria-label={`Add one ${p.name}`} disabled={i.quantity>=5} onClick={()=>update(i.id,i.size,i.quantity+1)}><Plus size={14}/></button><button className="remove-item" aria-label={`Remove ${p.name}`} onClick={()=>update(i.id,i.size,0)}><Trash2 size={15}/></button></div></div></article>;})}<div className="cart-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p className="muted small">Free sample shipping over ₹2,500. Redeem coins at checkout.</p><Link href="/checkout" className="button primary full" onClick={()=>setCartOpen(false)}>Continue to checkout <Arrow/></Link><p className="sample-note">Demo collection · No real payment or shipment</p></>}</div></Modal>;}
export function Footer(){return <footer className="footer"><div className="footer-head"><p>THE FUTURE<br/>IS <em>REBOUND.</em></p><Link href="/shop" className="circle-link" aria-label="Explore the collection"><MoveUpRight size={44}/></Link></div><div className="footer-grid"><div><Link href="/" className="wordmark">sūtra<span>REBIND</span></Link><p>Indian roots. Reimagined futures.<br/>70% rescued. 30% unexpected. 100% you.</p></div><div><h3>Explore</h3><Link href="/shop">The collection</Link><Link href="/passport">Garment passports</Link><Link href="/bank">Tukda Bank</Link></div><div><h3>Be part of it</h3><Link href="/rebind-bar">Rebind Bar</Link><Link href="/careers">Careers & challenges</Link><Link href="/contact">Contact us</Link></div><div><h3>Let’s talk</h3><a href={whatsapp()} target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={14}/></a><span>+91 93292 31248</span><p className="small">Made with intention.<br/>Designed to come back around.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sūtra Rebind</span><span className="mono">SAMPLE STORE / BUILT FOR CIRCULARITY</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Store information</Link><Link href="/admin">Studio access</Link></div></div></footer>;}
