'use client';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight,X,Check,LoaderCircle} from 'lucide-react';
import {ReactNode,useState,FormEvent} from 'react';
import {useShop} from './providers';
export function Arrow(){return <ArrowUpRight size={19} aria-hidden="true"/>;}
export function Modal({open,onOpenChange,title,description,children,drawer=false}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description?:string;children:ReactNode;drawer?:boolean}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className={drawer?'dialog drawer':'dialog'} aria-describedby={description?'modal-description':undefined}><Dialog.Title className="dialog-title">{title}</Dialog.Title>{description&&<Dialog.Description id="modal-description" className="muted">{description}</Dialog.Description>}<Dialog.Close className="icon-button dialog-close" aria-label="Close dialog"><X/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Field({label,name,type='text',required=true,placeholder,...props}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string;[key:string]:unknown}){return <label className="field"><span>{label}{required&&<span aria-hidden="true"> *</span>}</span><input name={name} type={type} required={required} placeholder={placeholder} {...props}/></label>;}
export function Select({label,name,options,...props}:{label:string;name:string;options:string[];[key:string]:unknown}){return <label className="field"><span>{label} *</span><select name={name} required {...props}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;}
export function Textarea({label,name,...props}:{label:string;name:string;[key:string]:unknown}){return <label className="field"><span>{label} *</span><textarea name={name} required rows={4} {...props}/></label>;}
export function Consent(){return <label className="check-label"><input name="consent" type="checkbox" required/><span>I agree to the <a href="/privacy" target="_blank" rel="noreferrer">privacy notice</a> and to being contacted about this request.</span></label>;}
export function Form({kind,extra={},children,button='Send request',success='Your request is saved. You can find it in your account.',onSuccess}:{kind:string;extra?:Record<string,unknown>;children:ReactNode;button?:string;success?:string;onSuccess?:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');const {refresh}=useShop();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const data={...Object.fromEntries(form),...extra,consent:form.get('consent')==='on'};try{const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})});const out=await r.json();if(!r.ok)throw new Error(out.error);setReference(out.id);await refresh();onSuccess?.();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 if(reference)return <div className="success-panel" role="status"><Check size={32}/><h3>Consider it received.</h3><p>{success}</p><p className="mono">REFERENCE / {reference.slice(0,8).toUpperCase()}</p><a className="text-link" href="/account">View your requests <Arrow/></a></div>;
 return <form onSubmit={submit} className="form-stack">{children}<Consent/>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={18}/> Saving…</>:<>{button}<Arrow/></>}</button></form>;
}
export function PageIntro({eyebrow,title,accent,description}:{eyebrow:string;title:string;accent?:string;description:string}){return <header className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}{accent&&<><br/><em>{accent}</em></>}</h1><p className="intro-copy">{description}</p></header>;}
export function SampleNote({children='Sample collection. Illustrative products, imagery and prices; checkout is in demo mode.'}:{children?:ReactNode}){return <p className="sample-note">{children}</p>;}
